language: node_js
node_js:
  - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database store-test-db;' -U postgres
  - psql -U postgres -d storetestdb -a -f store.sql

script:
  - npm test

after_script: npm run coverage
