env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPO_TOKEN
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - npm i -g codeclimate-test-reporter
script:
  - npm test
after_script:
  - CODECLIMATE_REPO_TOKEN=CC_TEST_REPORTER_ID codeclimate-test-reporter < coverage/lcov.info
